app_book:
    resource: |
        alias: app.book
    type: sylius.resource_api

#app_book_show:
#    path: /books/{id}
#    methods: [GET]
#    defaults:
#        _controller: app.controller.book:showAction
